[build]
builder = "RAILPACK"

[deploy]
startCommand = "python manage.py collectstatic --noinput && gunicorn core.wsgi:application"
preDeployCommand = "python manage.py migrate"

[deploy.variables]
RAILPACK_PYTHON_VERSION = "3.13"
