# Generated by Django 6.0.4 on 2026-04-25 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_chat_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуг')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('regions', models.TextField(help_text='Перечислите регионы через запятую', verbose_name='Регионы доставки')),
                ('transport_types', models.CharField(choices=[('truck', 'Грузовик'), ('van', 'Фургон'), ('motorcycle', 'Мотоцикл'), ('cargo_bike', 'Грузовой велосипед'), ('refrigerated', 'Рефрижератор')], default='truck', max_length=50, verbose_name='Тип транспорта')),
                ('price_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена за км (₸)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='delivery/logos/', verbose_name='Логотип компании')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирована')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_company', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транспортная компания',
                'verbose_name_plural': 'Транспортные компании',
            },
        ),
    ]
